// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package cqrs

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB5f7ac86DecodeGitlabComEtoshiBackendCommonVagoCqrs(in *jlexer.Lexer, out *sendMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.I = string(in.String())
		case "key":
			if in.IsNull() {
				in.Skip()
				out.AffinityKey = nil
			} else {
				if out.AffinityKey == nil {
					out.AffinityKey = new(string)
				}
				*out.AffinityKey = string(in.String())
			}
		case "version":
			out.V = string(in.String())
		case "resource":
			out.R = string(in.String())
		case "action":
			out.A = string(in.String())
		case "time":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.T).UnmarshalJSON(data))
			}
		case "payload":
			if m, ok := out.P.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.P.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.P = in.Interface()
			}
		case "user_id":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UserID).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB5f7ac86EncodeGitlabComEtoshiBackendCommonVagoCqrs(out *jwriter.Writer, in sendMsg) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.I))
	}
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix)
		if in.AffinityKey == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.AffinityKey))
		}
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.V))
	}
	{
		const prefix string = ",\"resource\":"
		out.RawString(prefix)
		out.String(string(in.R))
	}
	{
		const prefix string = ",\"action\":"
		out.RawString(prefix)
		out.String(string(in.A))
	}
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix)
		out.Raw((in.T).MarshalJSON())
	}
	{
		const prefix string = ",\"payload\":"
		out.RawString(prefix)
		if m, ok := in.P.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.P.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.P))
		}
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Raw((in.UserID).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v sendMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB5f7ac86EncodeGitlabComEtoshiBackendCommonVagoCqrs(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v sendMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB5f7ac86EncodeGitlabComEtoshiBackendCommonVagoCqrs(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *sendMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB5f7ac86DecodeGitlabComEtoshiBackendCommonVagoCqrs(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *sendMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB5f7ac86DecodeGitlabComEtoshiBackendCommonVagoCqrs(l, v)
}
