// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package cqrs

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF16d5208DecodeGitlabComEtoshiBackendCommonVagoCqrs(in *jlexer.Lexer, out *recvMsg) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.I = string(in.String())
		case "version":
			out.V = string(in.String())
		case "resource":
			out.R = string(in.String())
		case "action":
			out.A = string(in.String())
		case "time":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.T).UnmarshalJSON(data))
			}
		case "payload":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.P).UnmarshalJSON(data))
			}
		case "user_id":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UserID).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF16d5208EncodeGitlabComEtoshiBackendCommonVagoCqrs(out *jwriter.Writer, in recvMsg) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.I))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.V))
	}
	{
		const prefix string = ",\"resource\":"
		out.RawString(prefix)
		out.String(string(in.R))
	}
	{
		const prefix string = ",\"action\":"
		out.RawString(prefix)
		out.String(string(in.A))
	}
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix)
		out.Raw((in.T).MarshalJSON())
	}
	{
		const prefix string = ",\"payload\":"
		out.RawString(prefix)
		out.Raw((in.P).MarshalJSON())
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Raw((in.UserID).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v recvMsg) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF16d5208EncodeGitlabComEtoshiBackendCommonVagoCqrs(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v recvMsg) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF16d5208EncodeGitlabComEtoshiBackendCommonVagoCqrs(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *recvMsg) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF16d5208DecodeGitlabComEtoshiBackendCommonVagoCqrs(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *recvMsg) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF16d5208DecodeGitlabComEtoshiBackendCommonVagoCqrs(l, v)
}
