// Code generated by mockery v2.46.0. DO NOT EDIT.

package cqrs

import (
	context "context"

	"github.com/sonirico/vago/rp"
	mock "github.com/stretchr/testify/mock"
)

// MockCommandBus is an autogenerated mock type for the CommandBus type
type MockCommandBus struct {
	mock.Mock
}

type MockCommandBus_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandBus) EXPECT() *MockCommandBus_Expecter {
	return &MockCommandBus_Expecter{mock: &_m.Mock}
}

// CommandHandler provides a mock function with given fields: cmdHandler
func (_m *MockCommandBus) CommandHandler(cmdHandler CommandHandler) CommandBus {
	ret := _m.Called(cmdHandler)

	if len(ret) == 0 {
		panic("no return value specified for CommandHandler")
	}

	var r0 CommandBus
	if rf, ok := ret.Get(0).(func(CommandHandler) CommandBus); ok {
		r0 = rf(cmdHandler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(CommandBus)
		}
	}

	return r0
}

// MockCommandBus_CommandHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommandHandler'
type MockCommandBus_CommandHandler_Call struct {
	*mock.Call
}

// CommandHandler is a helper method to define mock.On call
//   - cmdHandler CommandHandler
func (_e *MockCommandBus_Expecter) CommandHandler(cmdHandler interface{}) *MockCommandBus_CommandHandler_Call {
	return &MockCommandBus_CommandHandler_Call{Call: _e.mock.On("CommandHandler", cmdHandler)}
}

func (_c *MockCommandBus_CommandHandler_Call) Run(run func(cmdHandler CommandHandler)) *MockCommandBus_CommandHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(CommandHandler))
	})
	return _c
}

func (_c *MockCommandBus_CommandHandler_Call) Return(_a0 CommandBus) *MockCommandBus_CommandHandler_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandBus_CommandHandler_Call) RunAndReturn(run func(CommandHandler) CommandBus) *MockCommandBus_CommandHandler_Call {
	_c.Call.Return(run)
	return _c
}

// close provides a mock function with given fields:
func (_m *MockCommandBus) close() {
	_m.Called()
}

// MockCommandBus_close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'close'
type MockCommandBus_close_Call struct {
	*mock.Call
}

// close is a helper method to define mock.On call
func (_e *MockCommandBus_Expecter) close() *MockCommandBus_close_Call {
	return &MockCommandBus_close_Call{Call: _e.mock.On("close")}
}

func (_c *MockCommandBus_close_Call) Run(run func()) *MockCommandBus_close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommandBus_close_Call) Return() *MockCommandBus_close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommandBus_close_Call) RunAndReturn(run func()) *MockCommandBus_close_Call {
	_c.Call.Return(run)
	return _c
}

// codec provides a mock function with given fields:
func (_m *MockCommandBus) codec() Codec {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for codec")
	}

	var r0 Codec
	if rf, ok := ret.Get(0).(func() Codec); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Codec)
		}
	}

	return r0
}

// MockCommandBus_codec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'codec'
type MockCommandBus_codec_Call struct {
	*mock.Call
}

// codec is a helper method to define mock.On call
func (_e *MockCommandBus_Expecter) codec() *MockCommandBus_codec_Call {
	return &MockCommandBus_codec_Call{Call: _e.mock.On("codec")}
}

func (_c *MockCommandBus_codec_Call) Run(run func()) *MockCommandBus_codec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommandBus_codec_Call) Return(_a0 Codec) *MockCommandBus_codec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandBus_codec_Call) RunAndReturn(run func() Codec) *MockCommandBus_codec_Call {
	_c.Call.Return(run)
	return _c
}

// commandHandler provides a mock function with given fields: x
func (_m *MockCommandBus) commandHandler(x Handler) (CommandHandler, bool) {
	ret := _m.Called(x)

	if len(ret) == 0 {
		panic("no return value specified for commandHandler")
	}

	var r0 CommandHandler
	var r1 bool
	if rf, ok := ret.Get(0).(func(Handler) (CommandHandler, bool)); ok {
		return rf(x)
	}
	if rf, ok := ret.Get(0).(func(Handler) CommandHandler); ok {
		r0 = rf(x)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(CommandHandler)
		}
	}

	if rf, ok := ret.Get(1).(func(Handler) bool); ok {
		r1 = rf(x)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockCommandBus_commandHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'commandHandler'
type MockCommandBus_commandHandler_Call struct {
	*mock.Call
}

// commandHandler is a helper method to define mock.On call
//   - x Handler
func (_e *MockCommandBus_Expecter) commandHandler(x interface{}) *MockCommandBus_commandHandler_Call {
	return &MockCommandBus_commandHandler_Call{Call: _e.mock.On("commandHandler", x)}
}

func (_c *MockCommandBus_commandHandler_Call) Run(run func(x Handler)) *MockCommandBus_commandHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(Handler))
	})
	return _c
}

func (_c *MockCommandBus_commandHandler_Call) Return(_a0 CommandHandler, _a1 bool) *MockCommandBus_commandHandler_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandBus_commandHandler_Call) RunAndReturn(run func(Handler) (CommandHandler, bool)) *MockCommandBus_commandHandler_Call {
	_c.Call.Return(run)
	return _c
}

// hasHandlers provides a mock function with given fields:
func (_m *MockCommandBus) hasHandlers() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for hasHandlers")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockCommandBus_hasHandlers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'hasHandlers'
type MockCommandBus_hasHandlers_Call struct {
	*mock.Call
}

// hasHandlers is a helper method to define mock.On call
func (_e *MockCommandBus_Expecter) hasHandlers() *MockCommandBus_hasHandlers_Call {
	return &MockCommandBus_hasHandlers_Call{Call: _e.mock.On("hasHandlers")}
}

func (_c *MockCommandBus_hasHandlers_Call) Run(run func()) *MockCommandBus_hasHandlers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommandBus_hasHandlers_Call) Return(_a0 bool) *MockCommandBus_hasHandlers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandBus_hasHandlers_Call) RunAndReturn(run func() bool) *MockCommandBus_hasHandlers_Call {
	_c.Call.Return(run)
	return _c
}

// id provides a mock function with given fields:
func (_m *MockCommandBus) id() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for id")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockCommandBus_id_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'id'
type MockCommandBus_id_Call struct {
	*mock.Call
}

// id is a helper method to define mock.On call
func (_e *MockCommandBus_Expecter) id() *MockCommandBus_id_Call {
	return &MockCommandBus_id_Call{Call: _e.mock.On("id")}
}

func (_c *MockCommandBus_id_Call) Run(run func()) *MockCommandBus_id_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommandBus_id_Call) Return(_a0 string) *MockCommandBus_id_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandBus_id_Call) RunAndReturn(run func() string) *MockCommandBus_id_Call {
	_c.Call.Return(run)
	return _c
}

// publish provides a mock function with given fields: ctx, msg
func (_m *MockCommandBus) publish(ctx context.Context, msg rp.Msg) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, rp.Msg) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandBus_publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'publish'
type MockCommandBus_publish_Call struct {
	*mock.Call
}

// publish is a helper method to define mock.On call
//   - ctx context.Context
//   - msg rp.Msg
func (_e *MockCommandBus_Expecter) publish(ctx interface{}, msg interface{}) *MockCommandBus_publish_Call {
	return &MockCommandBus_publish_Call{Call: _e.mock.On("publish", ctx, msg)}
}

func (_c *MockCommandBus_publish_Call) Run(run func(ctx context.Context, msg rp.Msg)) *MockCommandBus_publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rp.Msg))
	})
	return _c
}

func (_c *MockCommandBus_publish_Call) Return(_a0 error) *MockCommandBus_publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandBus_publish_Call) RunAndReturn(run func(context.Context, rp.Msg) error) *MockCommandBus_publish_Call {
	_c.Call.Return(run)
	return _c
}

// subscribe provides a mock function with given fields: ctx, handler
func (_m *MockCommandBus) subscribe(ctx context.Context, handler rp.ConsumerHandler) error {
	ret := _m.Called(ctx, handler)

	if len(ret) == 0 {
		panic("no return value specified for subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, rp.ConsumerHandler) error); ok {
		r0 = rf(ctx, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandBus_subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'subscribe'
type MockCommandBus_subscribe_Call struct {
	*mock.Call
}

// subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - handler rp.ConsumerHandler
func (_e *MockCommandBus_Expecter) subscribe(ctx interface{}, handler interface{}) *MockCommandBus_subscribe_Call {
	return &MockCommandBus_subscribe_Call{Call: _e.mock.On("subscribe", ctx, handler)}
}

func (_c *MockCommandBus_subscribe_Call) Run(run func(ctx context.Context, handler rp.ConsumerHandler)) *MockCommandBus_subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rp.ConsumerHandler))
	})
	return _c
}

func (_c *MockCommandBus_subscribe_Call) Return(_a0 error) *MockCommandBus_subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandBus_subscribe_Call) RunAndReturn(run func(context.Context, rp.ConsumerHandler) error) *MockCommandBus_subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// topic provides a mock function with given fields:
func (_m *MockCommandBus) topic() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for topic")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockCommandBus_topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'topic'
type MockCommandBus_topic_Call struct {
	*mock.Call
}

// topic is a helper method to define mock.On call
func (_e *MockCommandBus_Expecter) topic() *MockCommandBus_topic_Call {
	return &MockCommandBus_topic_Call{Call: _e.mock.On("topic")}
}

func (_c *MockCommandBus_topic_Call) Run(run func()) *MockCommandBus_topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommandBus_topic_Call) Return(_a0 string) *MockCommandBus_topic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandBus_topic_Call) RunAndReturn(run func() string) *MockCommandBus_topic_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommandBus creates a new instance of MockCommandBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandBus {
	mock := &MockCommandBus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
