// Code generated by mockery v2.46.0. DO NOT EDIT.

package cqrs

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockContainerOperator is an autogenerated mock type for the ContainerOperator type
type MockContainerOperator struct {
	mock.Mock
}

type MockContainerOperator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContainerOperator) EXPECT() *MockContainerOperator_Expecter {
	return &MockContainerOperator_Expecter{mock: &_m.Mock}
}

// Command provides a mock function with given fields: ctx, busID, cmd
func (_m *MockContainerOperator) Command(ctx context.Context, busID string, cmd CommandPayload) error {
	ret := _m.Called(ctx, busID, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Command")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, CommandPayload) error); ok {
		r0 = rf(ctx, busID, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContainerOperator_Command_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Command'
type MockContainerOperator_Command_Call struct {
	*mock.Call
}

// Command is a helper method to define mock.On call
//   - ctx context.Context
//   - busID string
//   - cmd CommandPayload
func (_e *MockContainerOperator_Expecter) Command(ctx interface{}, busID interface{}, cmd interface{}) *MockContainerOperator_Command_Call {
	return &MockContainerOperator_Command_Call{Call: _e.mock.On("Command", ctx, busID, cmd)}
}

func (_c *MockContainerOperator_Command_Call) Run(run func(ctx context.Context, busID string, cmd CommandPayload)) *MockContainerOperator_Command_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(CommandPayload))
	})
	return _c
}

func (_c *MockContainerOperator_Command_Call) Return(_a0 error) *MockContainerOperator_Command_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContainerOperator_Command_Call) RunAndReturn(run func(context.Context, string, CommandPayload) error) *MockContainerOperator_Command_Call {
	_c.Call.Return(run)
	return _c
}

// Event provides a mock function with given fields: ctx, busID, event
func (_m *MockContainerOperator) Event(ctx context.Context, busID string, event EventPayload) error {
	ret := _m.Called(ctx, busID, event)

	if len(ret) == 0 {
		panic("no return value specified for Event")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, EventPayload) error); ok {
		r0 = rf(ctx, busID, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContainerOperator_Event_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Event'
type MockContainerOperator_Event_Call struct {
	*mock.Call
}

// Event is a helper method to define mock.On call
//   - ctx context.Context
//   - busID string
//   - event EventPayload
func (_e *MockContainerOperator_Expecter) Event(ctx interface{}, busID interface{}, event interface{}) *MockContainerOperator_Event_Call {
	return &MockContainerOperator_Event_Call{Call: _e.mock.On("Event", ctx, busID, event)}
}

func (_c *MockContainerOperator_Event_Call) Run(run func(ctx context.Context, busID string, event EventPayload)) *MockContainerOperator_Event_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(EventPayload))
	})
	return _c
}

func (_c *MockContainerOperator_Event_Call) Return(_a0 error) *MockContainerOperator_Event_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContainerOperator_Event_Call) RunAndReturn(run func(context.Context, string, EventPayload) error) *MockContainerOperator_Event_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockContainerOperator creates a new instance of MockContainerOperator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContainerOperator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContainerOperator {
	mock := &MockContainerOperator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
