// Code generated by mockery v2.46.0. DO NOT EDIT.

package cqrs

import (
	context "context"

	"github.com/sonirico/vago/rp"
	mock "github.com/stretchr/testify/mock"
)

// MockEventBus is an autogenerated mock type for the EventBus type
type MockEventBus struct {
	mock.Mock
}

type MockEventBus_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventBus) EXPECT() *MockEventBus_Expecter {
	return &MockEventBus_Expecter{mock: &_m.Mock}
}

// EventHandler provides a mock function with given fields: eventHandler
func (_m *MockEventBus) EventHandler(eventHandler EventHandler) EventBus {
	ret := _m.Called(eventHandler)

	if len(ret) == 0 {
		panic("no return value specified for EventHandler")
	}

	var r0 EventBus
	if rf, ok := ret.Get(0).(func(EventHandler) EventBus); ok {
		r0 = rf(eventHandler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(EventBus)
		}
	}

	return r0
}

// MockEventBus_EventHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventHandler'
type MockEventBus_EventHandler_Call struct {
	*mock.Call
}

// EventHandler is a helper method to define mock.On call
//   - eventHandler EventHandler
func (_e *MockEventBus_Expecter) EventHandler(eventHandler interface{}) *MockEventBus_EventHandler_Call {
	return &MockEventBus_EventHandler_Call{Call: _e.mock.On("EventHandler", eventHandler)}
}

func (_c *MockEventBus_EventHandler_Call) Run(run func(eventHandler EventHandler)) *MockEventBus_EventHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(EventHandler))
	})
	return _c
}

func (_c *MockEventBus_EventHandler_Call) Return(_a0 EventBus) *MockEventBus_EventHandler_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventBus_EventHandler_Call) RunAndReturn(run func(EventHandler) EventBus) *MockEventBus_EventHandler_Call {
	_c.Call.Return(run)
	return _c
}

// SagaHandler provides a mock function with given fields: sagaHandler
func (_m *MockEventBus) SagaHandler(sagaHandler SagaHandler) EventBus {
	ret := _m.Called(sagaHandler)

	if len(ret) == 0 {
		panic("no return value specified for SagaHandler")
	}

	var r0 EventBus
	if rf, ok := ret.Get(0).(func(SagaHandler) EventBus); ok {
		r0 = rf(sagaHandler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(EventBus)
		}
	}

	return r0
}

// MockEventBus_SagaHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SagaHandler'
type MockEventBus_SagaHandler_Call struct {
	*mock.Call
}

// SagaHandler is a helper method to define mock.On call
//   - sagaHandler SagaHandler
func (_e *MockEventBus_Expecter) SagaHandler(sagaHandler interface{}) *MockEventBus_SagaHandler_Call {
	return &MockEventBus_SagaHandler_Call{Call: _e.mock.On("SagaHandler", sagaHandler)}
}

func (_c *MockEventBus_SagaHandler_Call) Run(run func(sagaHandler SagaHandler)) *MockEventBus_SagaHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(SagaHandler))
	})
	return _c
}

func (_c *MockEventBus_SagaHandler_Call) Return(_a0 EventBus) *MockEventBus_SagaHandler_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventBus_SagaHandler_Call) RunAndReturn(run func(SagaHandler) EventBus) *MockEventBus_SagaHandler_Call {
	_c.Call.Return(run)
	return _c
}

// close provides a mock function with given fields:
func (_m *MockEventBus) close() {
	_m.Called()
}

// MockEventBus_close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'close'
type MockEventBus_close_Call struct {
	*mock.Call
}

// close is a helper method to define mock.On call
func (_e *MockEventBus_Expecter) close() *MockEventBus_close_Call {
	return &MockEventBus_close_Call{Call: _e.mock.On("close")}
}

func (_c *MockEventBus_close_Call) Run(run func()) *MockEventBus_close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventBus_close_Call) Return() *MockEventBus_close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventBus_close_Call) RunAndReturn(run func()) *MockEventBus_close_Call {
	_c.Call.Return(run)
	return _c
}

// codec provides a mock function with given fields:
func (_m *MockEventBus) codec() Codec {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for codec")
	}

	var r0 Codec
	if rf, ok := ret.Get(0).(func() Codec); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Codec)
		}
	}

	return r0
}

// MockEventBus_codec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'codec'
type MockEventBus_codec_Call struct {
	*mock.Call
}

// codec is a helper method to define mock.On call
func (_e *MockEventBus_Expecter) codec() *MockEventBus_codec_Call {
	return &MockEventBus_codec_Call{Call: _e.mock.On("codec")}
}

func (_c *MockEventBus_codec_Call) Run(run func()) *MockEventBus_codec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventBus_codec_Call) Return(_a0 Codec) *MockEventBus_codec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventBus_codec_Call) RunAndReturn(run func() Codec) *MockEventBus_codec_Call {
	_c.Call.Return(run)
	return _c
}

// eventHandler provides a mock function with given fields: x
func (_m *MockEventBus) eventHandler(x Handler) (EventHandler, bool) {
	ret := _m.Called(x)

	if len(ret) == 0 {
		panic("no return value specified for eventHandler")
	}

	var r0 EventHandler
	var r1 bool
	if rf, ok := ret.Get(0).(func(Handler) (EventHandler, bool)); ok {
		return rf(x)
	}
	if rf, ok := ret.Get(0).(func(Handler) EventHandler); ok {
		r0 = rf(x)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(EventHandler)
		}
	}

	if rf, ok := ret.Get(1).(func(Handler) bool); ok {
		r1 = rf(x)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockEventBus_eventHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'eventHandler'
type MockEventBus_eventHandler_Call struct {
	*mock.Call
}

// eventHandler is a helper method to define mock.On call
//   - x Handler
func (_e *MockEventBus_Expecter) eventHandler(x interface{}) *MockEventBus_eventHandler_Call {
	return &MockEventBus_eventHandler_Call{Call: _e.mock.On("eventHandler", x)}
}

func (_c *MockEventBus_eventHandler_Call) Run(run func(x Handler)) *MockEventBus_eventHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(Handler))
	})
	return _c
}

func (_c *MockEventBus_eventHandler_Call) Return(_a0 EventHandler, _a1 bool) *MockEventBus_eventHandler_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventBus_eventHandler_Call) RunAndReturn(run func(Handler) (EventHandler, bool)) *MockEventBus_eventHandler_Call {
	_c.Call.Return(run)
	return _c
}

// hasHandlers provides a mock function with given fields:
func (_m *MockEventBus) hasHandlers() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for hasHandlers")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockEventBus_hasHandlers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'hasHandlers'
type MockEventBus_hasHandlers_Call struct {
	*mock.Call
}

// hasHandlers is a helper method to define mock.On call
func (_e *MockEventBus_Expecter) hasHandlers() *MockEventBus_hasHandlers_Call {
	return &MockEventBus_hasHandlers_Call{Call: _e.mock.On("hasHandlers")}
}

func (_c *MockEventBus_hasHandlers_Call) Run(run func()) *MockEventBus_hasHandlers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventBus_hasHandlers_Call) Return(_a0 bool) *MockEventBus_hasHandlers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventBus_hasHandlers_Call) RunAndReturn(run func() bool) *MockEventBus_hasHandlers_Call {
	_c.Call.Return(run)
	return _c
}

// id provides a mock function with given fields:
func (_m *MockEventBus) id() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for id")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockEventBus_id_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'id'
type MockEventBus_id_Call struct {
	*mock.Call
}

// id is a helper method to define mock.On call
func (_e *MockEventBus_Expecter) id() *MockEventBus_id_Call {
	return &MockEventBus_id_Call{Call: _e.mock.On("id")}
}

func (_c *MockEventBus_id_Call) Run(run func()) *MockEventBus_id_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventBus_id_Call) Return(_a0 string) *MockEventBus_id_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventBus_id_Call) RunAndReturn(run func() string) *MockEventBus_id_Call {
	_c.Call.Return(run)
	return _c
}

// publish provides a mock function with given fields: ctx, msg
func (_m *MockEventBus) publish(ctx context.Context, msg rp.Msg) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, rp.Msg) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventBus_publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'publish'
type MockEventBus_publish_Call struct {
	*mock.Call
}

// publish is a helper method to define mock.On call
//   - ctx context.Context
//   - msg rp.Msg
func (_e *MockEventBus_Expecter) publish(ctx interface{}, msg interface{}) *MockEventBus_publish_Call {
	return &MockEventBus_publish_Call{Call: _e.mock.On("publish", ctx, msg)}
}

func (_c *MockEventBus_publish_Call) Run(run func(ctx context.Context, msg rp.Msg)) *MockEventBus_publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rp.Msg))
	})
	return _c
}

func (_c *MockEventBus_publish_Call) Return(_a0 error) *MockEventBus_publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventBus_publish_Call) RunAndReturn(run func(context.Context, rp.Msg) error) *MockEventBus_publish_Call {
	_c.Call.Return(run)
	return _c
}

// sagaHandler provides a mock function with given fields: x
func (_m *MockEventBus) sagaHandler(x Handler) (SagaHandler, bool) {
	ret := _m.Called(x)

	if len(ret) == 0 {
		panic("no return value specified for sagaHandler")
	}

	var r0 SagaHandler
	var r1 bool
	if rf, ok := ret.Get(0).(func(Handler) (SagaHandler, bool)); ok {
		return rf(x)
	}
	if rf, ok := ret.Get(0).(func(Handler) SagaHandler); ok {
		r0 = rf(x)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(SagaHandler)
		}
	}

	if rf, ok := ret.Get(1).(func(Handler) bool); ok {
		r1 = rf(x)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockEventBus_sagaHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'sagaHandler'
type MockEventBus_sagaHandler_Call struct {
	*mock.Call
}

// sagaHandler is a helper method to define mock.On call
//   - x Handler
func (_e *MockEventBus_Expecter) sagaHandler(x interface{}) *MockEventBus_sagaHandler_Call {
	return &MockEventBus_sagaHandler_Call{Call: _e.mock.On("sagaHandler", x)}
}

func (_c *MockEventBus_sagaHandler_Call) Run(run func(x Handler)) *MockEventBus_sagaHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(Handler))
	})
	return _c
}

func (_c *MockEventBus_sagaHandler_Call) Return(_a0 SagaHandler, _a1 bool) *MockEventBus_sagaHandler_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEventBus_sagaHandler_Call) RunAndReturn(run func(Handler) (SagaHandler, bool)) *MockEventBus_sagaHandler_Call {
	_c.Call.Return(run)
	return _c
}

// subscribe provides a mock function with given fields: ctx, handler
func (_m *MockEventBus) subscribe(ctx context.Context, handler rp.ConsumerHandler) error {
	ret := _m.Called(ctx, handler)

	if len(ret) == 0 {
		panic("no return value specified for subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, rp.ConsumerHandler) error); ok {
		r0 = rf(ctx, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventBus_subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'subscribe'
type MockEventBus_subscribe_Call struct {
	*mock.Call
}

// subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - handler rp.ConsumerHandler
func (_e *MockEventBus_Expecter) subscribe(ctx interface{}, handler interface{}) *MockEventBus_subscribe_Call {
	return &MockEventBus_subscribe_Call{Call: _e.mock.On("subscribe", ctx, handler)}
}

func (_c *MockEventBus_subscribe_Call) Run(run func(ctx context.Context, handler rp.ConsumerHandler)) *MockEventBus_subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rp.ConsumerHandler))
	})
	return _c
}

func (_c *MockEventBus_subscribe_Call) Return(_a0 error) *MockEventBus_subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventBus_subscribe_Call) RunAndReturn(run func(context.Context, rp.ConsumerHandler) error) *MockEventBus_subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// topic provides a mock function with given fields:
func (_m *MockEventBus) topic() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for topic")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockEventBus_topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'topic'
type MockEventBus_topic_Call struct {
	*mock.Call
}

// topic is a helper method to define mock.On call
func (_e *MockEventBus_Expecter) topic() *MockEventBus_topic_Call {
	return &MockEventBus_topic_Call{Call: _e.mock.On("topic")}
}

func (_c *MockEventBus_topic_Call) Run(run func()) *MockEventBus_topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventBus_topic_Call) Return(_a0 string) *MockEventBus_topic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventBus_topic_Call) RunAndReturn(run func() string) *MockEventBus_topic_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventBus creates a new instance of MockEventBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventBus {
	mock := &MockEventBus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
