// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package cluster

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEc0cdf38DecodeGitlabComEtoshiBackendCommonVagoCluster(in *jlexer.Lexer, out *Session) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "last_updated":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.LastUpdated).UnmarshalJSON(data))
			}
		case "node_id":
			out.NodeID = string(in.String())
		case "service_id":
			out.ServiceID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEc0cdf38EncodeGitlabComEtoshiBackendCommonVagoCluster(out *jwriter.Writer, in Session) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"last_updated\":"
		out.RawString(prefix[1:])
		out.Raw((in.LastUpdated).MarshalJSON())
	}
	{
		const prefix string = ",\"node_id\":"
		out.RawString(prefix)
		out.String(string(in.NodeID))
	}
	{
		const prefix string = ",\"service_id\":"
		out.RawString(prefix)
		out.String(string(in.ServiceID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Session) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEc0cdf38EncodeGitlabComEtoshiBackendCommonVagoCluster(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Session) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEc0cdf38EncodeGitlabComEtoshiBackendCommonVagoCluster(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Session) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEc0cdf38DecodeGitlabComEtoshiBackendCommonVagoCluster(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Session) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEc0cdf38DecodeGitlabComEtoshiBackendCommonVagoCluster(l, v)
}
